(require 'cask "~/.cask/cask.el")
(cask-initialize)
(require 'pallet)

(add-to-list 'load-path "~/.emacs.d/package_config")

(load "00global.el")
(load "01ruby.el")
(load "02auto-complete.el")
(load "03smartparens.el")
(load "04projectile.el")
(load "05emmet.el")
(load "06rhtml.el")
(load "07web-mode.el")
(load "08multiple-cursors.el")
(load "09linum.el")
(load "10powerline.el")
(load "11flyspell.el")
(load "12yasnippet.el")
